apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: qtms-bookmarks-test-suite
  namespace: testkube
spec:
  description: "QTMS Bookmarks Test Suite"
  steps:
  - execute:
      stopOnFailure: true
      namespace: testkube
      name: qtms-bookmarks-playwright